#!/bin/bash

export EXTERNAL_IP=$(curl http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null)
export INTERNAL_IP=$(curl http://169.254.169.254/latest/meta-data/local-ipv4 2>/dev/null)

echo "Connect to ${INTERNAL_IP} ..."

sudo pke-etcd member list --endpoints ${INTERNAL_IP}:2379